# default paths to check for data
input_container: /home/etienne/Workspace/zebrafish-experiments/data/s16_bottom_110nm_rec_.n5
id_annotations_path: /home/etienne/Workspace/zebrafish-experiments/data/{organelle}-{sample}-{annotation_type}.txt
#dataset_container: /home/etienne/Workspace/zebrafish-experiments/data/s16_bottom_110nm_rec_2.n5
data_group: "/home/etienne/Workspace/zebrafish-experiments/data/volumes/{sample}"
raw_dataset: "/home/etienne/Workspace/zebrafish-experiments/data/volumes/{sample}/raw"
gt_dataset: "/home/etienne/Workspace/zebrafish-experiments/data/volumes/{sample}/{organelle}"
mask_dataset: "/home/etienne/Workspace/zebrafish-experiments/data/volumes/{sample}/{organelle}_mask"
points_dataset: "/home/etienne/Workspace/zebrafish-experiments/data/volumes/{sample}/{organelle}_points"
prediction_container: "/home/etienne/Workspace/zebrafish-experiments/data/predictions/zebrafish/zebrafish.n5"
sample_path: "/home/etienne/Workspace/zebrafish-experiments/data/adjavond/zebrafish/data"

data_problems:
    17-2:
        cells:
            id_mapping:
                - [34, 0]
                - [21, 0]
            mask_id: 81
    8-1:
        axons:
            id_mapping:
                - [8, 3]
            mask_id: 9
        cells:
            mask_id: 5
    8-2:
        axons:
            id_mapping:
                - [8, 6]
            mask_id: 12
        cells:
            mask_id: 3
        vessel:
            mask_id: 3
