# default paths to check for data
# used in reformat_dataset
input_container: /data/projects/punim2142/zebrafish_experiments/data/zebrafish_in.n5
# /groups/mousebrainmicro/home/pattonw/Data/michelle_zebrafish/zebrafish.n5

# used in reformat_dataset (relabel, maybe merge_mask?)
id_annotations_path: /data/projects/punim2142/zebrafish_experiments/data/id_annotations/{organelle}-{sample}-{annotation_type}.txt
# /groups/mousebrainmicro/home/pattonw/Data/michelle_zebrafish/id_annotations/{organelle}-{sample}-{annotation_type}.txt

# used in reformat_dataset, submit
dataset_container: /data/projects/punim2142/zebrafish_experiments/data/zebrafish.n5
# /nrs/funke/pattonw/data/zebrafish/zebrafish.n5

# not used
#data_group: "volumes/{sample}"

# used in datasets, predict_worker, predict, reformat_dataset (copy_data, relabel)
raw_dataset: "volumes/{sample}/raw"

# used in configs/scripts/datasplits/datasets.py, reformat_dataset (copy_data, update_masks, relabel, merge_masks)
gt_dataset: "volumes/{sample}/{organelle}"

# used in dataset, 02_extract_fragments_*, reformat_dataset (all 5)
mask_dataset: "volumes/{sample}/{organelle}_mask"

# used in datasets.py and reformat_dataset.py (generate_points)
points_dataset: "volumes/{sample}/{organelle}_points"

# only used in submit.py
prediction_container: "/data/projects/punim2142/zebrafish_experiments/data/predictions/zebrafish.n5"
# "/nrs/funke/pattonw/predictions/zebrafish/zebrafish.n5"

# not used
# sample_path: "/data/projects/punim2142/zebrafish_experiments/data/zebrafish/data"
# "/nrs/funke/adjavond/zebrafish/data"

# used in reformat_dataset (copy_data)
data_problems:
    17-2:
        cells:
            id_mapping:
                - [34, 0]
                - [21, 0]
            mask_id: 81
    8-1:
        axons:
            id_mapping:
                - [8, 3]
            mask_id: 9
        cells:
            mask_id: 5
    8-2:
        axons:
            id_mapping:
                - [8, 6]
            mask_id: 12
        cells:
            mask_id: 3
        vessel:
            mask_id: 3
