__type__: GunpowderTrainerConfig
augments:
- __type__: SimpleAugmentConfig
- __type__: ElasticAugmentConfig
  control_point_displacement_sigma:
  - 10.0
  - 10.0
  - 10.0
  control_point_spacing:
  - 100
  - 100
  - 100
  rotation_interval:
  - 0
  - 1.5707963267948966
  subsample: 8
  uniform_3d_rotation: true
- __type__: IntensityAugmentConfig
  clip: true
  scale:
  - 0.25
  - 1.75
  shift:
  - -0.5
  - 0.35
batch_size: 1
clip_raw: false
learning_rate: 0.0001
min_masked: 0.15
name: test-trainer
num_data_fetchers: 1
snapshot_interval: 1
