name: 2023-01-17
billing: funke
predictions:
  - outputs:
      - cells
    datasets:
      - name: 23_bot
        container: /nrs/funke/adjavond/zebrafish/data/s23_bottom_110nm_rec_.n5
        array: raw
      - name: 23_mid1
        container: /nrs/funke/adjavond/zebrafish/data/s23_mid1_110nm_rec_.n5
        array: raw
      - name: 23_top
        container: /nrs/funke/adjavond/zebrafish/data/s23_top_110nm_rec_.n5
        array: raw
    setups:
      - name: finetuned_3d_lsdaffs_zebrafish_cells_upsample-unet_default__1
        target: cells
    criteria:
      - "40000"
