name: 2023-01-30
billing: funke
predictions:
  - outputs:
      - vessel
    datasets:
      - name: 23_bot
        container: /nrs/funke/adjavond/zebrafish/data/s23_bottom_110nm_rec_.n5
        array: raw
    setups:
      - name: finetuned_3d_lsdaffs_zebrafish_vessel_upsample-unet_default__0
        target: vessel
    criteria:
      - "45000"
      - "60000"
  # - outputs:
  #     - axons
  #   datasets:
  #     - name: 23_bot
  #       container: /nrs/funke/adjavond/zebrafish/data/s23_bottom_110nm_rec_.n5
  #       array: raw
  #   setups:
  #     - name: finetuned_3d_lsdaffs_zebrafish_axons_upsample-unet_default__0
  #       target: axons
  #   criteria:
  #     - "30000"
  #   roi:
  #     - [512, 512, 512]
  #     - [1024, 1024, 1024]
  # - outputs:
  #     - axons
  #   datasets:
  #     - name: 23_bot
  #       container: /nrs/funke/adjavond/zebrafish/data/s23_bottom_110nm_rec_.n5
  #       array: raw
  #   setups:
  #     - name: scratch_3d_lsdaffs_zebrafish_axons_upsample-unet_default__0
  #       target: axons
  #   criteria:
  #     - "40000"
  #   roi:
  #     - [512, 512, 512]
  #     - [1024, 1024, 1024]
