name: 2023-02-06
billing: funke
predictions:
  - outputs:
      - axons
    datasets:
      - name: 16_bot
        container: /nrs/funke/adjavond/zebrafish/data/s16_bottom_110nm_rec_.n5
        array: raw
      - name: 23_bot
        container: /nrs/funke/adjavond/zebrafish/data/s23_bottom_110nm_rec_.n5
        array: raw
      - name: 23_mid1
        container: /nrs/funke/adjavond/zebrafish/data/s23_mid1_110nm_rec_.n5
        array: raw
      - name: 23_top
        container: /nrs/funke/adjavond/zebrafish/data/s23_top_110nm_rec_.n5
        array: raw
    setups:
      - name: scratch_3d_lsdaffs_zebrafish_axons_upsample-unet_default__1
        target: axons
    criteria:
      - "20000"
  - outputs:
      - vessel
    datasets:
      - name: 16_bot
        container: /nrs/funke/adjavond/zebrafish/data/s16_bottom_110nm_rec_.n5
        array: raw
      - name: 23_bot
        container: /nrs/funke/adjavond/zebrafish/data/s23_bottom_110nm_rec_.n5
        array: raw
      - name: 23_mid1
        container: /nrs/funke/adjavond/zebrafish/data/s23_mid1_110nm_rec_.n5
        array: raw
      - name: 23_top
        container: /nrs/funke/adjavond/zebrafish/data/s23_top_110nm_rec_.n5
        array: raw
    setups:
      - name: scratch_3d_lsdaffs_zebrafish_vessel_upsample-unet_default__0
        target: vessel
    criteria:
      - "35000"