name: 2023-02-02
billing: funke
predictions:
  - outputs:
      - axons
    datasets:
      - name: 23_bot
        container: /nrs/funke/adjavond/zebrafish/data/s23_bottom_110nm_rec_.n5
        array: raw
    setups:
      - name: scratch_3d_lsdaffs_zebrafish_axons_upsample-unet_default__1
        target: axons
    criteria:
      - "20000"
    roi:
      - [512, 512, 512]
      - [1024, 1024, 1024]
  - outputs:
      - axons
    datasets:
      - name: 23_bot
        container: /nrs/funke/adjavond/zebrafish/data/s23_bottom_110nm_rec_.n5
        array: raw
    setups:
      - name: scratch_3d_lsdaffs_zebrafish_axons_upsample-unet_default__1
        target: axons
    criteria:
      - "30000"
    roi:
      - [512, 512, 512]
      - [1024, 1024, 1024]
  - outputs:
      - axons
    datasets:
      - name: 23_bot
        container: /nrs/funke/adjavond/zebrafish/data/s23_bottom_110nm_rec_.n5
        array: raw
    setups:
      - name: scratch_3d_lsdaffs_zebrafish_axons_upsample-unet_default__0
        target: axons
    criteria:
      - "50000"
    roi:
      - [512, 512, 512]
      - [1024, 1024, 1024]
  - outputs:
      - axons
    datasets:
      - name: 23_bot
        container: /nrs/funke/adjavond/zebrafish/data/s23_bottom_110nm_rec_.n5
        array: raw
    setups:
      - name: finetuned_3d_lsdaffs_zebrafish_axons_upsample-unet_default__1
        target: axons
    criteria:
      - "35000"
    roi:
      - [512, 512, 512]
      - [1024, 1024, 1024]