- finetuned_3d_lsdaffs_zebrafish_axons_upsample-unet_default__0
- finetuned_3d_lsdaffs_zebrafish_axons_upsample-unet_default__1
- scratch_3d_lsdaffs_zebrafish_axons_upsample-unet_default__0
- scratch_3d_lsdaffs_zebrafish_axons_upsample-unet_default__1
